#!/bin/bash

# Script para criar Pull Request no GitHub

echo "=== CodeQ SDK Integration - Pull Request ==="
echo ""
echo "Branch criada: feature/java-nodejs-sdk-integration"
echo "Commit realizado com sucesso!"
echo ""
echo "Para fazer push e criar a PR, você tem duas opções:"
echo ""
echo "OPÇÃO 1: Usando GitHub CLI (gh)"
echo "----------------------------------------"
echo "gh auth login"
echo "git push -u origin feature/java-nodejs-sdk-integration"
echo "gh pr create --title 'feat(sdks): Add Java and Node.js SDKs with framework integrations' \\"
echo "  --body-file PR_DESCRIPTION.md \\"
echo "  --base main"
echo ""
echo "OPÇÃO 2: Manualmente via navegador"
echo "----------------------------------------"
echo "1. Configure suas credenciais:"
echo "   git remote set-url origin git@github.com:osvaldoandrade/codeq.git"
echo "   # ou use Personal Access Token"
echo ""
echo "2. Faça push da branch:"
echo "   git push -u origin feature/java-nodejs-sdk-integration"
echo ""
echo "3. Abra o navegador em:"
echo "   https://github.com/osvaldoandrade/codeq/compare/main...feature/java-nodejs-sdk-integration"
echo ""
echo "4. Preencha o template da PR com as informações de SDK_INTEGRATION_OVERVIEW.md"
echo ""
echo "=== Arquivos criados ==="
git diff --name-status main..feature/java-nodejs-sdk-integration | head -20
echo ""
echo "Total de arquivos: $(git diff --name-only main..feature/java-nodejs-sdk-integration | wc -l)"
